apiVersion: v1
kind: Pod
metadata:
  name: skaffold-test
  labels:
    app: skaffold-test
spec:
  containers:
    - name: skaffold-test
      image: dmitter/skaffold-test
---
apiVersion: v1
kind: Service
metadata:
  name: skaffold-test
spec:
  selector:
    app: skaffold-test
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
